commerce_payment.commerce_payment_gateway.plugin.diamano_pay_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    sandbox_token:
      type: string
      label: 'Sandbox token'
    production_token:
      type: string
      label: 'Production token'
    payment_methods:
      type: sequence
      label: 'Moyens de paiements'
      sequence:
        - type: string
